
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igqwpmwrwbfhhvbqhqxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncXdwbXdyd2JmaGh2YnFocXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjY3MTMsImV4cCI6MjA2MTk0MjcxM30.lY1FceQVTaQm9m4IznjhhLGvm55vTWtEsITM-7r4aLc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
